version: "2.4"

volumes:
  yocto-cooker-sstate-cache: 
    name: 'yocto-cooker-sstate-cache'
  yocto-cooker-dl-cache:
    name: 'yocto-cooker-dl-cache'

services:
  app:
    # Using a Dockerfile is optional, but included for completeness.
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        VARIANT: bullseye
    env_file:
      - ./.env
    environment:
      - WKS_FOLDER_BNAME=${WKS_FOLDER_BNAME}
    command: /bin/sh -c "while sleep 1000; do :; done"  

    volumes:
      - ..:/workspaces/${WKS_FOLDER_BNAME?err}:cached
      - yocto-cooker-sstate-cache:/var/lib/sstate-cache
      - yocto-cooker-dl-cache:/var/lib/dl-cache
